#!/usr/bin/env python3
"""
Measures forwarding latency and loss through a running MARSH Manager.

A FLIGHT_MODEL node streams HIGHRES_IMU with time_usec set to the monotonic send time,
and LISTENERS INSTRUMENTS nodes (subscribed to HIGHRES_IMU by component type) measure
the one-way latency on arrival. Sender and receivers run in separate processes so that
the sender's busy-wait pacing does not hold the receivers' GIL.

Requires the Python dialect generated by scripts/update_mavlink.py (dist/all_marsh.py).
"""

import argparse
import multiprocessing as mp
import socket
import sys
import threading
import time
from os import path

root_path = path.abspath(path.join(path.dirname(__file__), '..', '..'))


def now_us():
    return time.monotonic_ns() // 1000


def make_node(args, compid, node_type):
    """Returns the dialect module, socket and MAVLink instance of a node sending HEARTBEAT at 2 Hz"""
    sys.path.insert(0, args.dist)
    import all_marsh as dialect

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, 8 << 20)
    sock.bind(('127.0.0.1', 0))
    manager = (args.host, args.port)

    class Output:
        def write(self, buffer):
            sock.sendto(buffer, manager)

    mav = dialect.MAVLink(Output(), srcSystem=args.system, srcComponent=compid)
    mav.robust_parsing = True

    def send_heartbeats():
        while True:
            mav.heartbeat_send(getattr(dialect, node_type), dialect.MAV_AUTOPILOT_INVALID,
                               0, 0, dialect.MAV_STATE_ACTIVE)
            time.sleep(0.5)
    threading.Thread(target=send_heartbeats, daemon=True).start()

    return dialect, sock, mav


def receiver(args, compid, control, results):
    _, sock, mav = make_node(args, compid, 'MARSH_TYPE_INSTRUMENTS')
    sock.settimeout(0.05)
    latencies = []
    while True:
        if control.poll():
            if control.recv() == 'quit':
                return
            results.send(latencies)
            latencies = []
        try:
            data = sock.recv(4096)
        except socket.timeout:
            continue
        arrival = now_us()
        for msg in mav.parse_buffer(data) or []:
            if msg.get_type() == 'HIGHRES_IMU':
                latencies.append(arrival - msg.time_usec)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('-r', '--rates', default='100,500,1000,2000,4000',
                        help='comma separated message rates in Hz (default: %(default)s)')
    parser.add_argument('-d', '--duration', type=float, default=5.0,
                        help='seconds of streaming per rate (default: %(default)s)')
    parser.add_argument('-l', '--listeners', type=int, default=1,
                        help='number of subscribed receiver nodes (default: %(default)s)')
    parser.add_argument('--host', default='127.0.0.1')
    parser.add_argument('--port', type=int, default=24400)
    parser.add_argument('--system', type=int, default=1, help='system id of the test nodes')
    parser.add_argument('--dist', default=path.join(root_path, 'dist'),
                        help='directory containing all_marsh.py (default: %(default)s)')
    args = parser.parse_args()

    if not path.exists(path.join(args.dist, 'all_marsh.py')):
        sys.exit(f'all_marsh.py not found in {args.dist}, run scripts/update_mavlink.py')

    workers = []
    for i in range(args.listeners):
        control_parent, control_child = mp.Pipe()
        results_child, results_parent = mp.Pipe()
        process = mp.Process(target=receiver,
                             args=(args, 11 + i, control_child, results_child), daemon=True)
        process.start()
        workers.append((process, control_parent, results_parent))

    _, _, sender = make_node(args, 10, 'MARSH_TYPE_FLIGHT_MODEL')
    time.sleep(2.0)  # let all nodes register

    def collect():
        for _, control, _ in workers:
            control.send('flush')
        return [results.recv() for _, _, results in workers]
    collect()  # drop anything received during registration

    print(f"{'rate Hz':>8} {'sent':>7} {'recv':>8} {'loss %':>7} "
          f"{'p50 us':>8} {'p99 us':>8} {'max us':>8}", flush=True)
    for rate in [int(r) for r in args.rates.split(',')]:
        period = 1.0 / rate
        count = int(rate * args.duration)
        start = time.perf_counter()
        for i in range(count):
            target = start + i * period
            while time.perf_counter() < target:
                pass
            sender.highres_imu_send(now_us(), *([0.0] * 13), 0)
        time.sleep(1.0)  # drain

        latencies = sorted(sum(collect(), []))
        received = len(latencies)
        expected = count * args.listeners

        def percentile(q):
            return latencies[min(received - 1, int(q * received))] if received else float('nan')
        print(f'{rate:>8} {count:>7} {received:>8} {100 * (1 - received / expected):>7.1f} '
              f'{percentile(.5):>8} {percentile(.99):>8} {percentile(1):>8}', flush=True)

    for process, control, _ in workers:
        control.send('quit')
        process.join()


if __name__ == '__main__':
    main()
